#!/bin/zsh
set -eu

if [[ $# -ne 1 || $1 == -* ]]; then
  print -u2 "Usage: $0 AWTRIX_HOST"
  exit 2
fi

host=$1

curl --fail --silent --show-error \
  -X PATCH "http://${host}/api/v1/settings" \
  -H 'Content-Type: application/json' \
  --data-binary '{"autoBrightness":true,"autoTransition":true,"appDurationMs":7000,"transitionEffect":"Fade","transitionDurationMs":500}' >/dev/null

curl --fail --silent --show-error \
  -X PUT "http://${host}/api/v1/apps/order" \
  -H 'Content-Type: application/json' \
  --data-binary '{"order":["ccusage","tokens"],"disabled":["Time","Date","Temperature","Humidity","Battery"]}' >/dev/null

print 'Configured AWTRIX NG for cost and token apps with automatic brightness and a 500 ms fade.'
